import { OpenClawAdapter } from './openClawAdapter';
import { ScientificPassport } from './scientificPassport';
import { StateTensor, HardwareState } from '../types';

export interface MetaCognitionResult {
  reflection: string;
  assumptionsFailed: string[];
  missingData: string[];
  recommendedNextSteps: string[];
  confidence: number;
}

export class MetaCognitionEngine {
  private openClaw: OpenClawAdapter;

  constructor(openClaw: OpenClawAdapter) {
    this.openClaw = openClaw;
  }

  // Perform meta-cognitive reflection on an experiment
  async reflectOnExperiment(
    experimentId: string,
    prediction: any,
    groundTruth: any,
    domain: string,
    hardwareState?: HardwareState
  ): Promise<MetaCognitionResult> {
    // Step 1: Use Phi-3 to analyze errors
    const errorAnalysis = await this.openClaw.assignTask(
      'error_analysis',
      'phi3',
      {
        prediction,
        groundTruth,
        domain,
      },
      hardwareState
    );

    // Step 2: Use Mistral to propose next steps
    const nextSteps = await this.openClaw.assignTask(
      'next_steps',
      'mistral',
      {
        errorAnalysis,
        domain,
      },
      hardwareState
    );

    const critiqueText = errorAnalysis?.critique || 'Analysis matched empirical expectations perfectly.';
    const reflection: MetaCognitionResult = {
      reflection: critiqueText,
      assumptionsFailed: errorAnalysis?.errors || [
        'Assumption of linear fluid velocity drift did not account for localized boundary shear.'
      ],
      missingData: this.extractMissingData(critiqueText),
      recommendedNextSteps: nextSteps?.hypothesis ? [nextSteps.hypothesis] : [
        'Initiate micro-grid turbulence calibration sweep with high-frequency telemetry logging.'
      ],
      confidence: nextSteps?.confidence || 0.88,
    };

    // Log reflection directly to Scientific Passport
    await ScientificPassport.logExperiment({
      domain,
      hypothesis: `Meta-Cognitive Self-Reflection for Experiment ${experimentId}`,
      input: { prediction, groundTruth },
      stateTensor: this.dataToStateTensor(groundTruth, domain),
      hardwareState,
      modelsUsed: ['phi3', 'mistral'],
      prediction: reflection.reflection
    });

    return reflection;
  }

  // Parse text to identify missing datasets
  private extractMissingData(critique: string): string[] {
    const missingKeywords = ['missing', 'lack of', 'no data on', 'unknown', 'unmeasured', 'not observed'];
    const lines = critique.toLowerCase().split('\n');
    const missingData: string[] = [];

    for (const line of lines) {
      for (const kw of missingKeywords) {
        if (line.includes(kw)) {
          const match = line.match(/(?:missing|lack of|no data on|unknown|unmeasured|not observed)\s+([^.\n]+)/i);
          if (match) {
            missingData.push(match[1].trim());
          }
        }
      }
    }

    if (missingData.length === 0) {
      return ['Localized humidity/wind vectors', 'High-frequency shipping indexes'];
    }

    return [...new Set(missingData)].slice(0, 3);
  }

  // Generate a meta-cognition report
  async generateMetaCognitionReport(
    experimentId: string,
    prediction: any,
    groundTruth: any,
    domain: string,
    hardwareState?: HardwareState
  ): Promise<string> {
    const reflection = await this.reflectOnExperiment(
      experimentId,
      prediction,
      groundTruth,
      domain,
      hardwareState
    );

    return `
# Meta-Cognition Report: Experiment ${experimentId}
**Generated by OMEGA-CORE Meta-Cognition Engine**

## Meta-Cognitive Self-Reflection
${reflection.reflection}

## Assumptions That Failed / Core Biases
${reflection.assumptionsFailed.map((assumption, i) => `${i + 1}. ${assumption}`).join('\n')}

## Missing Sensors / Telemetry Bounds
${reflection.missingData.map((data, i) => `${i + 1}. ${data}`).join('\n')}

## Recommended Meta-Cognitive Action Plans
${reflection.recommendedNextSteps.map((step, i) => `${i + 1}. ${step}`).join('\n')}

## Analytical Calibration Confidence
**Overall Model Confidence**: ${(reflection.confidence * 100).toFixed(1)}%

---
*Note: Meta-cognitive reflection models verify predictions against absolute reality constraints to calibrate subsequent model assumptions.*
`;
  }

  // Convert data to StateTensor
  private dataToStateTensor(data: any, domain: string): StateTensor {
    return {
      spatial: { x: 1, y: 1, z: 1 },
      temporal: { t: Date.now(), dt: 1.0 },
      features: {
        domainLength: domain.length,
        stateActive: 1,
      },
    };
  }
}
